### ISSUE TITLE
Unable to specify where to find the py.test command

### ISSUE THREAD

**Issue by joenye** [alfredodeza/pytest.vim#60]
For my use case, I want to be able to run py.test with a custom prefix, so that it can be executed inside a docker container (e.g. `docker-compose exec my-app py.test ...`). Would it be possible to add this option?

**Comment by alfredodeza** [comment]
That is an interesting issue. Would you be expecting automatic detection of `my-app` or how would you propose configuring that to avoid a 'global' setting that would mess up other docker apps?

Another issue here is that the plugin does a lot of work identifying paths and locations, so if the output of the `exec` command reports paths form the container that don't really map to the local one it would break all those features.

Have you tried tinkering with this? You could just hard code your `exec` prefix on this line:

            let cmd = "py.test --tb=short " . a:path

So that it becomes:

            let cmd = "docker-compose exec my-app py.test --tb=short " . a:path
